# Generated by Django 2.2 on 2020-06-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listitem_tasklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='item',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='item',
            new_name='items',
        ),
    ]
